name: Build and Deploy C# Function

on:
  push:
    branches: ["main"] #se lance quand on push sur main

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
         dotnet-version: '8.0.x'
      
      - name: Run Test
        # Cette commande va scanner tous les projets de test de la solution
        run: dotnet test ./FunctionApp1.Tests/FunctionApp1.Tests.csproj --no-restore

      - name: Build Project
        run: dotnet build ./FunctionApp1/FunctionApp1.csproj --configuration Release   

      - name: Publish Artifacts
        run: dotnet publish ./FunctionApp1/FunctionApp1.csproj --configuration Release --output ./output

      # Cette étape échouera tant que vous n'avez pas de secret AZURE_FUNCTIONAPP_PUBLISH_PROFILE'

      - name: Deploy to Azure
        uses: Azure/functions-action@v1
        with:
          app-name: 'NomDeVotreAppAzure' # A remplacer plus tard
          package: './output'
          publish-profile: ${{secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        




